/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://27mbbbtvqrcz3lee7hiubrgyri.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ap7quaavw5ff5chabsm3woirfa",
    "aws_cognito_identity_pool_id": "us-east-1:4e5ae03b-7e66-451a-98bd-5f54656d8b6b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_b8PSBz6LY",
    "aws_user_pools_web_client_id": "67u31f1d30iac9c5cedcb1hsoj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "fgbtheatersstoragef2bb9-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
